CREATE TABLE [SOP_VersionTable] (
  [EffectiveDate] DATETIME ,
  [100-Rapid assessment] DOUBLE ,
  [101-BLCA field methods] DOUBLE ,
  [102-DINO field methods] DOUBLE ,
  [103-CANY field methods] DOUBLE ,
  [104-DINO measuring vegetation] DOUBLE ,
  [105-DINO facies mapping & grain size dist_] DOUBLE ,
  [106-CANY & DINO equip_ lists] DOUBLE ,
  [107-CANY field methods] DOUBLE ,
  [10-After each field season] DOUBLE ,
  [11-Data management] DOUBLE ,
  [12-Data analysis & reporting] DOUBLE ,
  [13-Revising the protocol] DOUBLE ,
  [14-BLCA field methods, DINO sentinel site set up] DOUBLE ,
  [14-Facies mapping] DOUBLE ,
  [15-CURE methods] DOUBLE ,
  [16-Total station surveying] DOUBLE ,
  [17-RTK surveying part 1] DOUBLE ,
  [18-RTK surveying part 2] DOUBLE ,
  [19-Remote sensing] DOUBLE ,
  [1-Prior to field season/equip_ lists] DOUBLE ,
  [20-CURE field methods] DOUBLE ,
  [2-Training observers] DOUBLE ,
  [3-GPS methods] DOUBLE ,
  [4-Sentinel site set up] DOUBLE ,
  [5-Photos] DOUBLE ,
  [6-Measuring vegetation] DOUBLE ,
  [6-Vegetation] DOUBLE ,
  [7-Hydrologic measurements] DOUBLE ,
  [8-Facies mapping & grain size dist_] DOUBLE ,
  [8-Surveying] DOUBLE ,
  [9-After each field visit] DOUBLE 
)
