CREATE TABLE [TableFieldFlags] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] UNIQUE  CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [TableRef] VARCHAR (255),
  [FieldRef] VARCHAR (255),
  [Flag_ID] LONG 
)
