CREATE TABLE [tlu_NCPN_Plants] (
  [Master_Family] VARCHAR (50),
  [Master_PLANT_Code] VARCHAR (20) CONSTRAINT [PrimaryKey] PRIMARY KEY  UNIQUE  NOT NULL ,
  [Master_Species] VARCHAR (50) CONSTRAINT [Master_Species] UNIQUE ,
  [UT_Family] VARCHAR (50),
  [CO_Family] VARCHAR (50),
  [WY_Family] VARCHAR (50),
  [Utah_PLANT_Code] VARCHAR (20),
  [Utah_Species] VARCHAR (50),
  [Co_PLANT_Code] VARCHAR (20),
  [Co_Species] VARCHAR (50),
  [Wy_PLANT_code] VARCHAR (20),
  [Wy_Species] VARCHAR (50),
  [Add_Synonyms] LONGTEXT ,
  [Taxonomic_Notes] LONGTEXT ,
  [Master_Common_Name] VARCHAR (50),
  [ARCH] VARCHAR (15),
  [BLCA] VARCHAR (15),
  [BRCA] VARCHAR (15),
  [CANY] VARCHAR (15),
  [CARE] VARCHAR (15),
  [CEBR] VARCHAR (15),
  [COLM] VARCHAR (15),
  [CURE] VARCHAR (15),
  [DINO (UT)] VARCHAR (15),
  [DINO (CO)] VARCHAR (15),
  [FOBU] VARCHAR (15),
  [GOSP] VARCHAR (15),
  [HOVE (UT)] VARCHAR (15),
  [HOVE (CO)] VARCHAR (15),
  [NABR] VARCHAR (15),
  [PISP] VARCHAR (15),
  [TICA] VARCHAR (15),
  [ZION] VARCHAR (15),
  [Lifeform] VARCHAR (255),
  [Duration] VARCHAR (255),
  [Nativity] VARCHAR (255),
  [Trinomial] BIT ,
  [Unique_Species] BIT ,
  [LU_Code] VARCHAR (25) CONSTRAINT [LU_Code] UNIQUE ,
  [Wetland_Code] VARCHAR (20),
  [Wetland_Code_Info_Source] VARCHAR (50),
  [Photosynthetic_Pathway] VARCHAR (5),
  [ProtectedStatusID] LONG ,
  [ProtectedStatusNotes] VARCHAR (255)
)
