CREATE TABLE [tsys_App_Defaults] (
  [Project] VARCHAR (50),
  [Park] VARCHAR (10),
  [User_name] VARCHAR (50),
  [Activity] VARCHAR (50),
  [UTM_Zone] VARCHAR (50),
  [Datum] VARCHAR (50),
  [Protocol_Name] VARCHAR (100),
  [Release_ID] VARCHAR (50),
  [Link_file_path] VARCHAR (255),
  [Backup_prompt_startup] BIT ,
  [Backup_prompt_exit] BIT ,
  [Compact_be_exit] BIT ,
  [Verify_links_startup] BIT ,
  [Panel] SHORT ,
  [Entry_Role] VARCHAR (32),
  [Timeframe] SHORT ,
  [Root_Path] VARCHAR (255),
  [Data_Path] VARCHAR (255),
  [Photo_Path] VARCHAR (255)
)
