dbMemo "SQL" ="INSERT INTO tbl_Tags_History ( Table_Name, Record_ID_Field_Name, Record_ID, Fiel"
    "d_Name, Value_New, Value_Old, Value_History_Notes, Contact_ID, Network_User_Name"
    ", Change_Date, Updated_Date )\015\012VALUES ('tbl_Tags', 'Tag_ID', '{44AF08CE-63"
    "2A-402F-B44C-1299385B9C8E}', 'Tag_Status', 'Retired (In Office)', 'Sapling', '20"
    "18 pre-season: update dead sapling tag statuses to Retired (In Office)', '201803"
    "27144817-533424019.813538', 'blcampbell', Now(), Now());\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
