dbMemo "SQL" ="INSERT INTO tsys_App_Defaults ( Project, Park, User_name, Activity, UTM_Zone, Da"
    "tum, Protocol_Name, Release_ID, Link_file_path, Backup_prompt_startup, Backup_pr"
    "ompt_exit, Compact_be_exit, Verify_links_startup, Panel, Entry_Role, Timeframe )"
    "\015\012VALUES ('NCRN Forest Vegetation Monitoring', '*', '2018_Field Season', '"
    "enter', '18N', 'NAD83', 2.3, 'Version 9.6.1.9009 (4/30/2018)', 'T:\\I&M\\MONITOR"
    "ING\\Forest_Vegetation\\Database\\Beta Versions\\2018\\ForestVeg_be.accdb', No, "
    "No, Yes, Yes, 1, 'SECONDARY', 2018);\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
