dbMemo "SQL" ="SELECT tbl_Locations.Plot_Name, tbl_Locations.Unit_Code, tbl_Locations.Unit_Grou"
    "p, tbl_Locations.Subunit_Code, tbl_Locations.Panel, tbl_Locations.Frame, tbl_Loc"
    "ations.GRTS_Order, tbl_Locations.Location_Status, tbl_Locations.Location_Notes, "
    "Count(Format([Event_Date],\"yyyymmdd\")) AS Event_Count, Min(Format([Event_Date]"
    ",\"yyyymmdd\")) AS Event_Earliest, Max(Format([Event_Date],\"yyyymmdd\")) AS Eve"
    "nt_Latest, tbl_Locations.Slope, tbl_Locations.Aspect, tbl_Locations.X_Coord AS U"
    "TM_18N_NAD83_X, tbl_Locations.Y_Coord AS UTM_18N_NAD83_Y, Format([Lat_WGS84],\"0"
    ".00000000\") AS Latitude, Format([Lon_WGS84],\"0.00000000\") AS Longitude\015\012"
    "FROM tbl_Locations LEFT JOIN tbl_Events ON tbl_Locations.Location_ID = tbl_Event"
    "s.Location_ID\015\012GROUP BY tbl_Locations.Plot_Name, tbl_Locations.Unit_Code, "
    "tbl_Locations.Unit_Group, tbl_Locations.Subunit_Code, tbl_Locations.Panel, tbl_L"
    "ocations.Frame, tbl_Locations.GRTS_Order, tbl_Locations.Location_Status, tbl_Loc"
    "ations.Location_Notes, tbl_Locations.Slope, tbl_Locations.Aspect, tbl_Locations."
    "X_Coord, tbl_Locations.Y_Coord, Format([Lat_WGS84],\"0.00000000\"), Format([Lon_"
    "WGS84],\"0.00000000\")\015\012ORDER BY tbl_Locations.Plot_Name;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
Begin
End
