dbMemo "SQL" ="INSERT INTO tsys_App_Defaults ( Project, Park, User_name, Activity, UTM_Zone, Da"
    "tum, Protocol_Name, Release_ID, Link_file_path, Backup_prompt_startup, Backup_pr"
    "ompt_exit, Compact_be_exit, Verify_links_startup, Panel, Entry_Role, Timeframe, "
    "Data_Path, Photo_Path, Root_Path )\015\012VALUES ('NCRN Forest Vegetation Monito"
    "ring', '*', '2020_Field_Season', 'enter', '18N', 'NAD83', '2.3', 'Version 9.8.0."
    "9000 (5/5/2020)', 'T:\\I&M\\MONITORING\\FOREST_VEGETATION\\08_DATA\\2020\\Forest"
    "Veg_be.accdb', 0, 0, 1, 1, 3, 'OFFICE', 2020, 'FOREST_VEGETATION\\08_DATA\\', '_"
    "PHOTOS\\FOREST_VEGETATION\\', 'T:\\I&M\\MONITORING\\');\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
